# Generated by Django 5.2.6 on 2025-09-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_benefit_idx_benefit_segment_active_and_more"),
        ("customers", "0002_customer_idx_customer_segment_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client_req_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="idx_order_customer_status"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="idx_order_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["requested_delivery_date"], name="idx_order_delivery_date"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="idx_orderitem_order"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="ck_order_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_total__gte", 0)),
                name="ck_order_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_total__gte", 0)),
                name="ck_order_tax_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)),
                name="ck_order_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_window_to__gte", models.F("delivery_window_from")),
                    ("delivery_window_from__isnull", True),
                    ("delivery_window_to__isnull", True),
                    _connector="OR",
                ),
                name="ck_order_valid_delivery_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_req_id__isnull", False)),
                fields=("client_req_id",),
                name="uq_order_client_req_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="ck_orderitem_price_non_negative",
            ),
        ),
    ]
