# Generated by Django 5.2.6 on 2025-09-23 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_client_req_id_order_idx_order_customer_status_and_more"),
        ("stock", "0004_add_reservation_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp de la entrega",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="success",
                        help_text="Estado de la entrega",
                        max_length=10,
                    ),
                ),
                (
                    "total_movements",
                    models.PositiveIntegerField(
                        help_text="Número total de movimientos creados"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre la entrega",
                        null=True,
                    ),
                ),
                (
                    "error_details",
                    models.TextField(
                        blank=True,
                        help_text="Detalles del error si la entrega falló",
                        null=True,
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        help_text="Usuario que realizó la entrega",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Orden entregada",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAuditLogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_delivered",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad entregada del lote",
                        max_digits=12,
                    ),
                ),
                (
                    "movement_id",
                    models.PositiveIntegerField(
                        help_text="ID del movimiento EXIT creado"
                    ),
                ),
                (
                    "audit_log",
                    models.ForeignKey(
                        help_text="Registro de auditoría padre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.deliveryauditlog",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        help_text="Lote entregado",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.stocklot",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="deliveryauditlog",
            index=models.Index(
                fields=["order", "delivered_at"], name="idx_audit_order_date"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryauditlog",
            index=models.Index(
                fields=["delivered_by", "delivered_at"], name="idx_audit_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryauditlog",
            index=models.Index(
                fields=["status", "delivered_at"], name="idx_audit_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryauditlogitem",
            index=models.Index(
                fields=["audit_log", "lot"], name="idx_audit_item_log_lot"
            ),
        ),
    ]
