# Generated by Django 5.1.4 on 2025-09-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=160)),
                (
                    "segment",
                    models.CharField(
                        choices=[("wholesale", "Wholesale"), ("retail", "Retail")],
                        max_length=16,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("tax_id", models.CharField(blank=True, max_length=32)),
                ("tax_condition", models.CharField(blank=True, max_length=32)),
                (
                    "min_shelf_life_days",
                    models.IntegerField(
                        default=0,
                        help_text="Días mínimos de vida útil requeridos para este cliente",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["segment"], name="idx_customer_segment"),
                    models.Index(fields=["tax_id"], name="idx_customer_tax_id"),
                ],
            },
        ),
    ]
