# Generated by Django 5.2.6 on 2025-09-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["segment"], name="idx_customer_segment"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tax_id"], name="idx_customer_tax_id"),
        ),
    ]
