# Generated by Django 5.2.6 on 2025-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_idx_customer_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="min_shelf_life_days",
            field=models.IntegerField(
                default=0,
                help_text="Días mínimos de vida útil requeridos para este cliente",
            ),
        ),
    ]
