# Generated by Django 5.2.6 on 2025-09-12 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_benefit_idx_benefit_segment_active_and_more"),
        ("orders", "0002_order_client_req_id_order_idx_order_customer_status_and_more"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(
                fields=["product", "created_at"], name="idx_movement_product_date"
            ),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(
                fields=["type", "created_at"], name="idx_movement_type_date"
            ),
        ),
    ]
