# Generated by Django 5.2.6 on 2025-09-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_movement_idx_movement_product_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklot",
            name="is_quarantined",
            field=models.BooleanField(
                default=False, help_text="Lote en cuarentena, no disponible para venta"
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="is_reserved",
            field=models.BooleanField(
                default=False,
                help_text="Lote reservado, no disponible para asignación automática",
            ),
        ),
    ]
