# Generated by Django 5.2.6 on 2025-09-23 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_pack_size_alter_product_unit_and_more"),
        ("orders", "0002_order_client_req_id_order_idx_order_customer_status_and_more"),
        ("stock", "0003_stocklot_is_quarantined_stocklot_is_reserved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad reservada del lote",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Estado de la reserva",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="movement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("adjustment", "Adjustment"),
                    ("return_customer", "Return from Customer"),
                    ("return_supplier", "Return to Supplier"),
                    ("transfer", "Transfer"),
                    ("damage", "Damage"),
                    ("expiry", "Expiry"),
                ],
                default="adjustment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stocklot",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stock.warehouse"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(
                fields=[
                    "product",
                    "warehouse",
                    "is_quarantined",
                    "is_reserved",
                    "expiry_date",
                ],
                name="idx_lot_fefo_pick",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("type", "exit"),
                    models.Q(
                        ("type", "entry"),
                        ("lot__isnull", False),
                        ("unit_cost__isnull", False),
                        ("unit_cost__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="ck_movement_entry_requires_lot_and_cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("type", "entry"),
                    models.Q(("type", "exit"), ("lot__isnull", False)),
                    _connector="OR",
                ),
                name="ck_movement_exit_requires_lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_cost__gt", 0)),
                name="ck_lot_unit_cost_positive",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="lot",
            field=models.ForeignKey(
                help_text="Lote específico reservado",
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="order",
            field=models.ForeignKey(
                help_text="Orden para la cual se reserva el stock",
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["order", "status"], name="idx_reservation_order_status"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["lot", "status"], name="idx_reservation_lot_status"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["lot", "status", "qty"], name="idx_reservation_availability"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["created_at"], name="idx_reservation_created"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("qty__gt", 0)), name="ck_reservation_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("order", "lot"), name="uq_reservation_order_lot"
            ),
        ),
    ]
