# Generated by Django 5.2.6 on 2025-09-26 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_add_reservation_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockIdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("entry", "Stock Entry"), ("exit", "Stock Exit")],
                        max_length=10,
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(
                        help_text="Hash of request payload", max_length=64
                    ),
                ),
                ("response_data", models.JSONField(help_text="Original response data")),
                (
                    "status_code",
                    models.IntegerField(
                        help_text="HTTP status code of original response"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this key expires", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_idempotency_keys",
                "indexes": [
                    models.Index(
                        fields=["operation_type", "created_at"],
                        name="stock_idemp_operati_5e8ff3_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="stock_idemp_expires_81b144_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status_code__gte", 200), ("status_code__lt", 600)
                        ),
                        name="ck_stock_idempotency_valid_status_code",
                    )
                ],
            },
        ),
    ]
