# Generated by Django 5.2.6 on 2025-09-12 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_scope_users",
                    models.BooleanField(
                        default=False, verbose_name="Gestión de Usuarios"
                    ),
                ),
                (
                    "has_scope_dashboard",
                    models.BooleanField(default=True, verbose_name="Dashboard"),
                ),
                (
                    "has_scope_inventory",
                    models.BooleanField(default=False, verbose_name="Inventario"),
                ),
                (
                    "has_scope_orders",
                    models.BooleanField(default=False, verbose_name="Pedidos"),
                ),
                (
                    "has_scope_customers",
                    models.BooleanField(default=False, verbose_name="Clientes"),
                ),
                (
                    "has_scope_reports",
                    models.BooleanField(default=False, verbose_name="Reportes"),
                ),
                (
                    "has_scope_analytics",
                    models.BooleanField(default=False, verbose_name="Analytics"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scope de Usuario",
                "verbose_name_plural": "Scopes de Usuarios",
            },
        ),
    ]
