# Generated by Django 5.1.4 on 2025-09-23 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("vendedor_caja", "Vendedor de Caja"),
                            ("vendedor_ruta", "Vendedor de Ruta"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Nombre del Rol",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_scope_users",
                    models.BooleanField(
                        default=False, verbose_name="Gestión de Usuarios"
                    ),
                ),
                (
                    "has_scope_dashboard",
                    models.BooleanField(default=True, verbose_name="Dashboard"),
                ),
                (
                    "has_scope_inventory",
                    models.BooleanField(default=False, verbose_name="Inventario"),
                ),
                (
                    "has_scope_orders",
                    models.BooleanField(default=False, verbose_name="Pedidos"),
                ),
                (
                    "has_scope_customers",
                    models.BooleanField(default=False, verbose_name="Clientes"),
                ),
                (
                    "has_scope_reports",
                    models.BooleanField(default=False, verbose_name="Reportes"),
                ),
                (
                    "has_scope_analytics",
                    models.BooleanField(default=False, verbose_name="Analytics"),
                ),
                (
                    "has_scope_pos_override",
                    models.BooleanField(default=False, verbose_name="Override POS"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="panel.role",
                        verbose_name="Roles del Usuario",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scope de Usuario",
                "verbose_name_plural": "Scopes de Usuarios",
            },
        ),
    ]
