# Generated by Django 5.2.6 on 2025-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscope",
            name="has_scope_pos_override",
            field=models.BooleanField(default=False, verbose_name="Override POS"),
        ),
    ]
