# Generated by Django 5.2.6 on 2025-09-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_userscope_has_scope_pos_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("vendedor_caja", "Vendedor de Caja"),
                            ("vendedor_ruta", "Vendedor de Ruta"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Nombre del Rol",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="userscope",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="panel.role",
                verbose_name="Roles del Usuario",
            ),
        ),
    ]
