# Generated by Django 5.2.6 on 2025-09-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_role_userscope_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscope",
            name="has_scope_caja",
            field=models.BooleanField(default=False, verbose_name="Gestión de Caja"),
        ),
        migrations.AddField(
            model_name="userscope",
            name="has_scope_catalog",
            field=models.BooleanField(
                default=False, verbose_name="Catálogo de Productos"
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="has_scope_inventory_level_1",
            field=models.BooleanField(
                default=False, verbose_name="Inventario Nivel 1 (Básico)"
            ),
        ),
        migrations.AddField(
            model_name="userscope",
            name="has_scope_inventory_level_2",
            field=models.BooleanField(
                default=False, verbose_name="Inventario Nivel 2 (Completo)"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("encargado", "Encargado"),
                    ("vendedor_caja", "Vendedor de Caja"),
                    ("vendedor_ruta", "Vendedor de Ruta"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Nombre del Rol",
            ),
        ),
    ]
