services:
  # Django Backend - Development Configuration
  web:
    command: >
      sh -c "/app/docker/init_data.sh &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - VITE_API_BASE_URL=http://localhost/api

  # Celery Worker - Development Configuration
  worker:
    volumes:
      - ..:/app
      - media_volume:/app/media

  # Celery Beat Scheduler - Development Configuration
  beat:
    volumes:
      - ..:/app

  # POS Frontend - Development Configuration with Hot Reload
  pos-frontend:
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ../POS/workspace:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost/api
      - NODE_ENV=development
    ports:
      - "5173:5173"

  # Nginx - Development Configuration
  nginx:
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static:ro
      - media_volume:/var/www/media:ro
    ports:
      - "80:80"
      - "443:443"

  # MailHog - Development Email Testing
  mailhog:
    ports:
      - "8025:8025"