# Generated by Django 5.2.6 on 2025-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[("discount", "Discount"), ("combo", "Combo")],
                        max_length=16,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[("wholesale", "Wholesale"), ("retail", "Retail")],
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("combo_spec", models.JSONField(blank=True, null=True)),
                ("active_from", models.DateField()),
                ("active_to", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(db_index=True, max_length=160)),
                ("brand", models.CharField(blank=True, max_length=80)),
                ("unit", models.CharField(default="UN", max_length=8)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
