# Generated by Django 5.2.6 on 2025-09-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["segment", "is_active"], name="idx_benefit_segment_active"
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["active_from", "active_to"], name="idx_benefit_date_range"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category"], name="idx_product_active_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="benefit",
            constraint=models.CheckConstraint(
                check=models.Q(("active_to__gte", models.F("active_from"))),
                name="ck_benefit_valid_date_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="benefit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("value__gte", 0), ("value__isnull", True), _connector="OR"
                ),
                name="ck_benefit_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", 0)), name="ck_product_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("tax_rate__gte", 0)),
                name="ck_product_tax_rate_non_negative",
            ),
        ),
    ]
