# Generated by Django 5.2.6 on 2025-09-22 00:18

import django.contrib.postgres.indexes
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_trigram_extension"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="benefit",
            name="ck_benefit_value_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="ck_product_tax_rate_non_negative",
        ),
        migrations.AddField(
            model_name="benefit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="benefit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("UN", "Unidad"), ("KG", "Kilogramo"), ("LT", "Litro")],
                default="UN",
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(fields=["type"], name="idx_benefit_type"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="idx_product_brand"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="gin_product_name_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["code"],
                name="gin_product_code_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="benefit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("type", "discount"),
                        ("value__gte", 0),
                        ("value__isnull", False),
                        ("value__lte", 100),
                    ),
                    ("type", "combo"),
                    _connector="OR",
                ),
                name="ck_benefit_discount_value_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="benefit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("combo_spec__isnull", False), ("type", "combo")),
                    ("type", "discount"),
                    _connector="OR",
                ),
                name="ck_benefit_combo_spec_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 100)),
                name="ck_product_tax_rate_valid",
            ),
        ),
    ]
