# Generated by Django 5.2.6 on 2025-09-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_benefit_ck_benefit_value_non_negative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pack_size",
            field=models.IntegerField(
                blank=True, help_text="Número de unidades por paquete", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("unit", "Unidad"),
                    ("package", "Paquete"),
                    ("KG", "Kilogramo"),
                    ("LT", "Litro"),
                ],
                default="unit",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pack_size__isnull", True), ("pack_size__gt", 0), _connector="OR"
                ),
                name="ck_product_pack_size_positive",
            ),
        ),
    ]
