# Generated by Django 5.2.6 on 2025-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_pack_size_alter_product_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[("wholesale", "Wholesale"), ("retail", "Retail")],
                help_text="Segmento de mercado objetivo (opcional)",
                max_length=16,
                null=True,
            ),
        ),
    ]
