# Generated by Django 5.1.4 on 2025-09-23 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotOverrideAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_id",
                    models.CharField(
                        db_index=True, help_text="UUID de la venta POS", max_length=36
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "reason",
                    models.TextField(help_text="Razón proporcionada para el override"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot_chosen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.stocklot"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor", "timestamp"], name="idx_audit_actor_time"
                    ),
                    models.Index(fields=["sale_id"], name="idx_audit_sale"),
                    models.Index(
                        fields=["product", "timestamp"], name="idx_audit_prod_time"
                    ),
                    models.Index(
                        fields=["lot_chosen", "timestamp"], name="idx_audit_lot_time"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("qty__gt", 0)), name="ck_audit_qty_positive"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleItemLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_id",
                    models.CharField(
                        db_index=True, help_text="UUID de la venta POS", max_length=36
                    ),
                ),
                (
                    "item_sequence",
                    models.PositiveIntegerField(
                        help_text="Posición del ítem en la venta"
                    ),
                ),
                ("qty_consumed", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.stocklot"
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.movement"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sale_id"], name="idx_sale_item_lot_sale"),
                    models.Index(
                        fields=["sale_id", "item_sequence"],
                        name="idx_sale_item_lot_item",
                    ),
                    models.Index(
                        fields=["product", "created_at"],
                        name="idx_sale_item_lot_prod_date",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("qty_consumed__gt", 0)),
                        name="ck_sale_item_lot_qty_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("item_sequence__gt", 0)),
                        name="ck_sale_item_lot_sequence_positive",
                    ),
                ],
            },
        ),
    ]
