# Generated by Django 5.2.6 on 2025-09-16 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_benefit_idx_benefit_segment_active_and_more"),
        ("pos", "0001_initial"),
        ("stock", "0003_stocklot_is_quarantined_stocklot_is_reserved"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleItemLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_id",
                    models.CharField(
                        db_index=True, help_text="UUID de la venta POS", max_length=36
                    ),
                ),
                (
                    "item_sequence",
                    models.PositiveIntegerField(
                        help_text="Posición del ítem en la venta"
                    ),
                ),
                ("qty_consumed", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.stocklot"
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.movement"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sale_id"], name="idx_sale_item_lot_sale"),
                    models.Index(
                        fields=["sale_id", "item_sequence"],
                        name="idx_sale_item_lot_item",
                    ),
                    models.Index(
                        fields=["product", "created_at"],
                        name="idx_sale_item_lot_prod_date",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("qty_consumed__gt", 0)),
                        name="ck_sale_item_lot_qty_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("item_sequence__gt", 0)),
                        name="ck_sale_item_lot_sequence_positive",
                    ),
                ],
            },
        ),
    ]
