# Generated by Django 5.1.4 on 2025-09-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("new_order", "New Order"),
                            ("low_stock", "Low Stock"),
                            ("near_expiry", "Near Expiry"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("panel", "Panel"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"],
                        name="idx_notification_event_date",
                    ),
                    models.Index(
                        fields=["channel", "sent_at"],
                        name="idx_notification_channel_sent",
                    ),
                    models.Index(
                        fields=["created_at"], name="idx_notification_created"
                    ),
                    models.Index(fields=["sent_at"], name="idx_notification_sent"),
                ],
            },
        ),
    ]
