# Generated by Django 5.2.6 on 2025-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("new_order", "New Order"),
                            ("low_stock", "Low Stock"),
                            ("near_expiry", "Near Expiry"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("panel", "Panel"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
