# Generated by Django 5.2.6 on 2025-09-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event", "created_at"], name="idx_notification_event_date"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["channel", "sent_at"], name="idx_notification_channel_sent"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["created_at"], name="idx_notification_created"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["sent_at"], name="idx_notification_sent"),
        ),
    ]
